name: chat_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core:
  cloud_firestore:
  firebase_auth:
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  provider: ^6.0.5
  firebase_messaging: ^14.6.5
  flutter_launcher_icons: ^0.13.1
  flutter_colorpicker: ^1.0.3
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "Images/cloud_messaging.png"
  

  

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
